### ISSUE TITLE
Add it to packagist.org

### ISSUE THREAD

**Issue by gtrias** [oldskool/WhoopsCakephp#11]
In order to be able to do ``composer require oldskool/whoops-cakephp`` you should add the package to packagist.org.

Otherwise I have to set manually the repository on ``composer.json``

**Comment by tanuck** [comment]
It is already registered with packagist. See here: https://packagist.org/packages/oldskool/whoops-cakephp

**Comment by gtrias** [comment]
Wow I didn't found it.

Well I got this error trying to require it:

```
    - The requested package oldskool/woops-cakephp could not be found in any version, there may be a typo in the package name.
```

Changing version to dev-master make it works

**Comment by tanuck** [comment]
There is a typo in the package name you are using: `woops-cakephp` whereas it should be `whoops-cakephp`. Your missed the `h`.

**Comment by gtrias** [comment]
That's right. Thanks.

When I added to composer.json by hand it was ok.
